insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/125497','SBI Mutual Fund - SBI Small & Midcap - Direct Plan - Growth',' R. Srinivasan');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119670','SBI Mutual Fund - SBI Dynamic Bond Fund - DIRECT PLAN - Dividend','Dinesh Ahuja');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119598','SBI Mutual Fund - SBI BLUE CHIP FUND-DIRECT PLAN -GROWTH','Sohini Andani');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119821','SBI Mutual Fund - SBI SAVINGS FUND - DIRECT PLAN - GROWTH','R Arun');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119715','SBI Mutual Fund - SBI Magnum MIDCAP FUND - DIRECT PLAN -DIVIDEND','Sohini Andani');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/133036','Kotak Mahindra Mutual Fund - Kotak Balance - Growth','Pankaj Tibrewal / Abhishek Bisen');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/103234','Kotak Mahindra Mutual Fund - Kotak Opportunities---Growth','Harsha Upadhaya');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/103233','Kotak Mahindra Mutual Fund - Kotak Opportunities---Dividend','Harsha Upadhaya');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/120164','Kotak Mahindra Mutual Fund - Kotak-Mid-Cap-Growth - Direct','Pankaj Tibrewal');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119773','Kotak Mahindra Mutual Fund - Kotak Tax Saver-Scheme-Growth - Direct','Harsha Upadhyaya');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/133300','Birla Sun Life Mutual Fund - Birla Sun Life Emerging Leaders Fund - Series 5 - Regular Plan - Growth','Jayesh Gandhi');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/131738','Birla Sun Life Mutual Fund - Birla Sun Life Tax Savings Fund - Regular Plan - Bonus Option','Ajay Garg');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/106873','Birla Sun Life Mutual Fund - Birla Sun Life International Equity Fund - Plan A - Growth - Regular Plan','Vineet Maloo');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/125595','Birla Sun Life Mutual Fund - Birla Sun Life Banking and Financial Services Fund - Regular Plan - Growth','Satyabrata Mohanty / Dhaval Gala');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/111812','Birla Sun Life Mutual Fund - Birla Sun Life Medium Term Plan - Dividend - Regular Plan','Maneesh Dangi / Sunaina Da Cunha');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/114564','Axis Mutual Fund - Axis Midcap Fund - Growth','Ashish Naik');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/113434','Axis Mutual Fund - Axis Gold ETF','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/120479','Axis Mutual Fund - Axis Income Saver - Direct Plan - Quarterly','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/135122','Axis Mutual Fund - Axis Equity Saver Fund - Regular Plan - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/112323','Axis Mutual Fund - Axis Long Term Equity Fund - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/105872','DSP BlackRock Mutual Fund - DSP BlackRock Top 100 Equity Fund - Institutional Plan - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119076','DSP BlackRock Mutual Fund - DSP BlackRock Equity Fund - Direct Plan - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/136563','DSP BlackRock Mutual Fund - DSP BlackRock Equity Savings Fund - Regular Plan - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/101304','DSP BlackRock Mutual Fund - DSP BlackRock Short Term Fund- Regular Plan -Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119219','DSP BlackRock Mutual Fund - DSP BlackRock Opportunities Fund - Direct Plan - Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/100865','LIC Mutual Fund - LIC MF Taxplan-Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/136473','LIC Mutual Fund - LIC MF EXCHANGE TRADED FUND- NIFTY 100','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/120285','LIC Mutual Fund - LIC MF Children Fund Direct Plan','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/105823','LIC Mutual Fund - LIC MF INCOME PLUS FUND - GROWTH OPTION','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/101198','LIC Mutual Fund - LIC MF Index Fund-Sensex-Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/100385','Reliance Mutual Fund - Reliance Income Fund - Half Yearly Dividend Plan','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/130653','Reliance Mutual Fund - Reliance Capital Builder Fund- Series A- Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/118666','Reliance Mutual Fund - Reliance Growth Fund - Direct Plan Dividend Plan','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/106236','Reliance Mutual Fund - Reliance Top 200 Fund- Dividend Plan','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/111754','Reliance Mutual Fund - Reliance Money Manager Fund -Weekly Dividend Plan','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/112628','L&T Mutual Fund - L&T Income Opportunities Retail -Cumulative','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/112537','L&T Mutual Fund - L&T Tax Saver Fund-Dividend Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/112495','L&T Mutual Fund - L&T Mid Cap Fund-Regular Plan-Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/112600','L&T Mutual Fund - L&T Infrastructure Fund - Regular Plan - Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/118043','L&T Mutual Fund - L&T Equity Fund-Regular Plan-Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/100682','UTI Mutual Fund - UTI - Retirement Benefit Pension Fund','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/131511','UTI Mutual Fund - UTI - Floating Rate STP - Fortnightly Div Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/120665','UTI Mutual Fund - UTI - TOP 100 Fund- Growth Option - Direct','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/133869','UTI Mutual Fund - UTI Bond Fund - Annual Div Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/100806','UTI Mutual Fund - UTI Pharma & Healthcare Fund-Income Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/101980','HDFC Mutual Fund - HDFC TaxSaver-Dividend Plan','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/101586','HDFC Mutual Fund - HDFC Equity Savings Fund - DIVIDEND','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/102947','HDFC Mutual Fund - HDFC Premier Multi-Cap Fund-Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/118955','HDFC Mutual Fund - HDFC Equity Fund -Direct Plan - Growth Option','');
"insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/130498
','HDFC Mutual Fund - HDFC Large Cap Fund - Direct Growth Plan','');"
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/102141','ICICI Prudential Mutual Fund - ICICI Prudential Dynamic Accrual Plan - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/109740','ICICI Prudential Mutual Fund - ICICI Prudential Income Opportunities Fund - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/130932','ICICI Prudential Mutual Fund - ICICI Prudential Income Opportunities Fund - Bonus','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/102594','ICICI Prudential Mutual Fund - ICICI Prudential Value Discovery Fund - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/100349','ICICI Prudential Mutual Fund - ICICI Prudential Top 100 Fund - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/101815','PRINCIPAL Mutual Fund - Principal Personal Tax Saver Fund','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/103453','PRINCIPAL Mutual Fund - Principal Services Industries Fund-DIVIDEND','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/101118','PRINCIPAL Mutual Fund - Principal Government Securities Fund-Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/102337','PRINCIPAL Mutual Fund - Principal Global Opportunities Fund-Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/101119','PRINCIPAL Mutual Fund - Principal Government Securities Fund-Dividend Option- Annually','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/106370','Sundaram Mutual Fund - Sundaram Global Advantage Fund Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119545','Sundaram Mutual Fund - Sundaram Balanced Fund - Direct Plan - Dividend Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/134967','Sundaram Mutual Fund - Sundaram Income Plus - Direct Plan - Weekly Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119578','Sundaram Mutual Fund - Sundaram Select Focus - Direct Plan - Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/103743','Sundaram Mutual Fund - Sundaram Rural India Fund Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/139865','Motilal Oswal Mutual Fund - MOSt Focused Dynamic Equity - Direct Plan - Quarterly Dividend Payout Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/129047','Motilal Oswal Mutual Fund - MOSt Focused Multicap 35- Direct Plan-Dividend Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/127039','Motilal Oswal Mutual Fund - MOSt Focused Midcap 30-Regular Plan-Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/139870','Motilal Oswal Mutual Fund - MOSt Focused Dynamic Equity - Regular Plan - Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/139872','Motilal Oswal Mutual Fund - MOSt Focused Dynamic Equity - Direct Plan - Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/102016','Tata Mutual Fund - Tata Gilt High Fund - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/111778','Tata Mutual Fund - Tata Infrastructure Tax Saving Fund - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119251','Tata Mutual Fund - Tata Retirement Savings Fund-Direct Plan Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/101672','Tata Mutual Fund - Tata Equity P/E Fund Regular Plan -(Growth Option)','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/119231','Tata Mutual Fund - Tata Equity P/E Fund -Direct Plan Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/131356','IDFC Mutual Fund - IDFC DEF_Direct Plan_Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/139201','IDFC Mutual Fund - IDFC CBF_Direct Plan_Annual Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/139840','IDFC Mutual Fund - IDFC Sensex ETF','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/139839','IDFC Mutual Fund - IDFC Nifty ETF','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/118469','IDFC Mutual Fund - IDFC Infrastructure Fund-Direct Plan-Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/118529','Franklin Templeton Mutual Fund - Franklin India Low Duration Fund - Direct - Quarterly Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/113135','Franklin Templeton Mutual Fund - Franklin India Low Duration Fund - Growth Plan','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/118530','Franklin Templeton Mutual Fund - Franklin India Low Duration Fund - Direct - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/100522','Franklin Templeton Mutual Fund - Franklin India Technology Fund-Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/118462','Franklin Templeton Mutual Fund - Franklin India Bluechip Fund- Direct -Dividend','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/138459','DHFL Pramerica Mutual Fund - DHFL Pramerica Income Advantage Fund - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/138423','DHFL Pramerica Mutual Fund - DHFL Pramerica Low Duration Fund - GR','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/138470','DHFL Pramerica Mutual Fund - DHFL Pramerica Gilt Fund - Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/138391','DHFL Pramerica Mutual Fund - DHFL Pramerica Tax Plan-GROWTH','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/138264','DHFL Pramerica Mutual Fund - DHFL Pramerica Short Maturity Fund - Bonus','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/116424','Indiabulls Mutual Fund - Indiabulls Ultra Short Term Fund - Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/116548','Indiabulls Mutual Fund - Indiabulls Blue Chip Fund - Dividend Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/133181','Indiabulls Mutual Fund - Indiabulls Arbitrage Fund - Direct Plan - Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/121153','Indiabulls Mutual Fund - Indiabulls Income Fund - Direct Plan - Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/116547','Indiabulls Mutual Fund - Indiabulls Blue Chip Fund - Growth Option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/109523','JM Financial Mutual Fund - JM Multi Strategy Fund - Dividend option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/100234','JM Financial Mutual Fund - JM High Liquidity Fund-Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/109522','JM Financial Mutual Fund - JM Multi Strategy Fund - Growth option','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/103780','JM Financial Mutual Fund - JM ARBITRAGE ADVANTAGE FUND-Growth','');
insert into performance.mutual_fund(fund_id,fund_name,fund_manager) values('AMFI/133407','JM Financial Mutual Fund - JM Balanced Fund - Annual Bonus Option','');
